#!/bin/bash

######################
#UBuntu 20.04.1 LTS
#Apache 2.4.41 
#Install WordPress 
######################


# Set password (Prod change within mysql or pass in 1st arg)
# if arg $1 is (null -z) then default pw is 7h15is@hardpA$sw0rd
mysqlPass=$1
if [ -z $1 ]; then
	mysqlPass='7h15is@hardpA$sw0rd'
fi

# Stop process if there is an error
set -e

# Find Update
sudo apt-get update &&

# Install Update w/o Menu
sudo DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade &&

# Install Apache, PHP, and MySQL
sudo apt-get install -y apache2 php libapache2-mod-php mariadb-server mariadb-client php-mysql &&

# Root Pass \n -> Set Pass y\n -> Enter Pass1 7h15is@hardpA$sw0rd\n -> Enter Pass2 7h15is@hardpA$sw0rd\n -> Remove Anonymous y\n -> Disable Remote y\n -> Remove TestDB y\n -> Reload Privs y\n
# Root User plugin=unix_socket(LogIn via Root) change rootPass wont matter; To use password [update mysql.user set plugin="mysql_native_password" where User='root';]
(printf "\ny\n$mysqlPass\n$mysqlPass\ny\ny\ny\ny\n" | sudo mysql_secure_installation) &&

# Secure mariaDB step1 remove local-infile
# grep find if (local-infile=0) exist (if false ||) sed (in-place -i [make changes to file not only show]) find (mysqld escape bracket) then (/a append) 
grep -q "local-infile=0" /etc/mysql/mariadb.conf.d/50-server.cnf || sudo sed -i '/\[mysqld\]/a local-infile=0' /etc/mysql/mariadb.conf.d/50-server.cnf 
#restart mariaDB
&& sudo systemctl restart mariadb








#config file
#/etc/mysql/mariadb.conf.d/50-server.cnf
#SHOW GLOBAL VARIABLES LIKE 'local_infile';

# output fd 1&2 to terminal and log.out file 
#exec &> >(tee -a log.out)

#if [ "$1" == 'test' ]; then
#	echo "working"
#else
#	echo 'Not Working' 1>&2
#fi


# i.e. running remote script locally
#bash <(curl -s https://raw.githubusercontent.com/anoluck/AWS/master/testBash?token=AEGHN476YQOICJYKZ64DMR3A4KJ64) test
