#!/bin/bash

######################
#UBuntu 20.04.1 LTS
#Apache 2.4.41 
#Install WordPress 
######################

# Stop process if there is an error
set -e

# Find Update
sudo apt-get update &&

# Install Update w/o Menu
sudo DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade &&

# Install Apache, PHP, and MySQL
sudo apt-get install -y apache2 php libapache2-mod-php mariadb-server mariadb-client php-mysql &&

# Root Pass \n -> Set Pass y\n -> Enter Pass1 7h15is@hardpA$sw0rd\n -> Enter Pass2 7h15is@hardpA$sw0rd\n -> Remove Anonymous y\n -> Disable Remote y\n -> Remove TestDB y\n -> Reload Privs y\n
# Root User plugin=unix_socket(LogIn via Root) change rootPass wont matter; To use password [update mysql.user set plugin="mysql_native_password" where User='root';]
printf "\ny\n7h15is@hardpA$sw0rd\n7h15is@hardpA$sw0rd\ny\ny\ny\ny\n" | sudo mysql_secure_installation


#config file
#/etc/mysql/mariadb.conf.d/50-server.cnf
#SHOW GLOBAL VARIABLES LIKE 'local_infile';

# output fd 1&2 to terminal and log.out file 
#exec &> >(tee -a log.out)

#if [ "$1" == 'test' ]; then
#	echo "working"
#else
#	echo 'Not Working' 1>&2
#fi


# i.e. running remote script locally
#bash <(curl -s https://raw.githubusercontent.com/anoluck/AWS/master/testBash?token=AEGHN476YQOICJYKZ64DMR3A4KJ64) test