#!/bin/bash

# Stop process if there is an error
set -e

# output fd 1&2 to terminal and log.out file 
exec &> >(tee -a log.out)

if [ "$1" == 'test' ]; then
	echo "working"
else
	echo 'Not Working' 1>&2
fi


# i.e. running remote script locally
#bash <(curl -s https://raw.githubusercontent.com/anoluck/AWS/master/testBash?token=AEGHN476YQOICJYKZ64DMR3A4KJ64) test